name: Install Dependencies

on:
  push:
    branches:
      - abdu-exprimental  # Change this to the branch you are working on
  workflow_dispatch:  # Allows manual trigger

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Compress node_modules
        run: tar -czf node_modules.tar.gz node_modules

      - name: Upload node_modules as artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: node_modules
          path: node_modules.tar.gz
